### ISSUE TITLE
Support for K8s 1.14+

### ISSUE THREAD

**Issue by JoeJasinski** [willthames/kubernetes-validate#1]
Looks like an interesting project, thank you for putting it together. It would be great if this supported k8s 1.14-1.16.

**Comment by willthames** [comment]
Hi @JoeJasinski thanks for the nudge. I'll try and get that sorted soon.

**Comment by willthames** [comment]
I've just uploaded version 1.16.0 to pypi, which includes 1.14 through 1.16 (and removes 1.8 through 1.10)
