### ISSUE TITLE
Kubernetes 1.21 support on pypi.org

### ISSUE THREAD

**Issue by shk3bq4d** [willthames/kubernetes-validate#10]
Hello,

While there exists a release in this git repository for kubernetes v1.21.0 (dc2bf3b), current latest listed on https://pypi.org/project/kubernetes-validate/#history is 1.20.0

Is there anything that could be done to update pypi.org?

Best regards!

**Comment by willthames** [comment]
@shk3bq4d sorry I missed this earlier - looks like I failed to push it!

I'll try and sort that out in the next couple of days, but feel free to nudge if that doesn't happen

**Comment by shk3bq4d** [comment]
@willthames : gentle nudge ;-) But take your time!

**Comment by willthames** [comment]
@shk3bq4d thanks for the gentle nudge!

I've uploaded 1.21 and *also* created and uploaded a 1.22 version.
