### ISSUE TITLE
Kubernetes-validate should support version 1.24.0 and up

### ISSUE THREAD

**Issue by esteban20304** [willthames/kubernetes-validate#13]
As soon as we updated to Kubernetes version 1.24.0, we started receiving the message "Kubernetes version v1.24.0 is not supported by kubernetes-validate". Please support this version.

**Comment by willthames** [comment]
Hmm, I should probably fix it so that it validates against the most recent version rather than just fail. 

Thanks for raising this, I'll try and get it sorted shortly

**Comment by willthames** [comment]
Can you confirm you're running kubernetes-validate with `-k v1.24.0`? 

As my understanding is that the default is to validate against the latest version that kubernetes-validate knows about. 

I'll add the v1.24.0 resources though.
