### ISSUE TITLE
Compatibility with Python v3.12

### ISSUE THREAD

**Issue by brent-cybrid** [willthames/kubernetes-validate#24]
The import:

```python
    from distutils.version import LooseVersion
```

is incompatible with Python v3.12 (see [here](https://docs.python.org/3.10/library/distutils.html) for the note that `distutils` is no longer supported in Python v3.12).

This limitation prevents this package from being used in v3.12 environments.

**Comment by willthames** [comment]
Thanks for this - it seems like it's not just distutils but also pkg_resources.

#26 tracks the work for this.

**Comment by willthames** [comment]
#26 is pretty much ready but will drop support for python 3.8 - as such I'll combine it with the update for kubernetes 1.29 (which won't happen until after the upstream release expected in the next three days)

**Comment by willthames** [comment]
I'll release this as 1.28.3 soon (I've used importlib_resources backport to retain 3.8 compatibility so don't need a breaking change) - I think it's going to be a few days before I'm ready for 1.29

**Comment by willthames** [comment]
1.28.3 has now been released with 3.12 support
