### ISSUE TITLE
kubernetes 1.29

### ISSUE THREAD

**Issue by willthames** [willthames/kubernetes-validate#29]
Adding this issue to save others the effort

I've been updating my implementation of openapi2jsonschema to fix some deprecations but have broken it for now

As such 1.29 will likely be a few days (hopefully not weeks)

**Comment by willthames** [comment]
This is fixed in #30.

If anyone reading this wishes to test it out, it's on pypi as 1.29.0rc0 (so needs installing with `pip install --pre kubernetes-validate==1.29.0rc0`)

**Comment by anuragjanghala** [comment]
maybe not related to this thread but I had a question in any case does it support k3s version such as v1.28.4+k3s2

**Comment by willthames** [comment]
Hi @anuragjanghala , kubernetes-validate doesn't really care about server versions as it works completely offline.

It'll either validate using the latest version (currently 1.28 but 1.29 once #30 is merged) or a version you can pass using the `-k` flag (e.g. `kubernetes-validate -k 1.26 --strict manifest.yml`)

Given that my understanding is that k3s is pretty much entirely API compatible with kubernetes, validating any k3s version is just a matter of picking the right major version or choosing latest

**Comment by willthames** [comment]
1.29.0 and 1.29.1 have been released to pypi
