### ISSUE TITLE
Missing schemas for Kubernetes 1.30

### ISSUE THREAD

**Issue by lahwaacz** [willthames/kubernetes-validate#32]
Schemas for Kubernetes 1.30.1 are missing:

    FATAL kubernetes-validate 1.29.1 does not support kubernetes version 1.30.1

Getting this because the [k8s](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html) Ansible module defaults to the version of the server it is connected to.

**Comment by willthames** [comment]
I've pushed 1.30.0 to pypi: https://pypi.org/project/kubernetes-validate/1.30.0/

**Comment by lahwaacz** [comment]
Thanks, can you also make a [GitHub release](https://github.com/willthames/kubernetes-validate/releases)?

**Comment by willthames** [comment]
@lahwaacz sure, done
