### ISSUE TITLE
Kubernetes version v1.28.10+a2c84a5 is not supported by kubernetes-validate

### ISSUE THREAD

**Issue by gr33npr** [willthames/kubernetes-validate#35]
Hello, 

we have OpenShift Server Version: 4.15.19 with Kubernetes Version v1.28.10+a2c84a5. Running kubernetes-validate against it, leads to the following error-message:

`Kubernetes version v1.28.10+a2c84a5 is not supported by kubernetes-validate"`

I think Kubernetes 1.28 is supported, but maybe the additional string "+a2c84a5" (Built?) isnt recognized by kubernetes-validate.

Kind regards,
Sascha

**Comment by willthames** [comment]
I've had a dig into the source code and kubernetes-validate only checks whether the version you're asking for is newer than the latest version kubernetes-validate knows about

I've also checked and it seems to work for your version:

```
kubernetes-validate -k v1.28.10+a2c84a5 tests/kuard-extra-property.yaml
INFO tests/kuard-extra-property.yaml passed for resource deployment/kuard against version 1.28
```

So there are two possibilities here:
* you're using an older version of kubernetes-validate that doesn't support v1.28 - you need to upgrade
* whatever is passing in the version is doing it wrong and we should fix it there (ansible being the likeliest candidate)
