### ISSUE TITLE
Kubernetes 1.19 support

### ISSUE THREAD

**Issue by karlism** [willthames/kubernetes-validate#5]
Hello,

Are there any plans on implementing k8s 1.19 support?

I'm getting following warnings while deploying `networking.k8s.io/v1` resources on k8s 1.19:
```
[WARNING]: Ingress prometheus: Could not find schema for object kind Ingress with API version
networking.k8s.io/v1 in Kubernetes version 1.19.3 (possibly Custom Resource?)
```

Thanks!

**Comment by willthames** [comment]
Hi @karlism there are no plans *not* to implement 1.19! Sorry I haven't got around to it yet, but thank you for the reminder - I'll try and start that process now.

**Comment by willthames** [comment]
I've pushed v1.19.0 to pypi so hopefully that should work - I can see the code change contains
src/kubernetes_validate/kubernetes-json-schema/v1.19.0-local-strict/ingress-networking-v1.json

**Comment by karlism** [comment]
@willthames, thanks a lot, that was quick! I will test it later today.

**Comment by karlism** [comment]
Just tested it with various resources, including `networking.k8s.io/v1`, and it's working like charm. Thanks a lot!
